$terminal = kitty
$fileManager = nautilus

exec-once = swaybg -m solid -c 000000
exec-once = waybar
exec-once = swaync
exec-once = ~/dotfiles/core/scripts/focus_listener.sh

# Actualizar entorno para servicios systemd --user y reiniciar EmeBotEme
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY
exec-once = systemctl --user restart emeboteme.service