# Tamano del cursor para aplicaciones X11/XWayland.
env = XCURSOR_SIZE,24
# Tamano del cursor para el manejo nativo en Hyprland/Wayland.
env = HYPRCURSOR_SIZE,24
# Prioriza Wayland en aplicaciones Qt, con fallback a X11 si hace falta.
env = QT_QPA_PLATFORM,wayland;xcb
# Usa decoraciones del lado del servidor en Qt/Wayland para evitar doble barra de titulo.
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# Prioriza Wayland en aplicaciones GTK, permitiendo fallback a X11.
env = GDK_BACKEND,wayland,x11,*
# Fuerza que apps SDL (juegos/emuladores) usen backend Wayland.
env = SDL_VIDEODRIVER,wayland
# Prioriza backend Wayland para aplicaciones basadas en Clutter.
env = CLUTTER_BACKEND,wayland
# Permite que apps Electron elijan automaticamente Ozone (normalmente Wayland en Hyprland).
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Intel GPU
env = LIBVA_DRIVER_NAME,iHD
env = MESA_LOADER_DRIVER_NAME,iris
# env = __GLX_VENDOR_LIBRARY_NAME,mesa # A veces ayuda si hay problemas con GLX


